# Generated by Django 4.2.5 on 2023-10-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_id',
            field=models.FileField(blank=True, null=True, upload_to='rental/photo_ids/'),
        ),
    ]
