# Generated by Django 4.2.5 on 2023-10-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_userprofile_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_id',
            field=models.FileField(blank=True, null=True, upload_to='photo_ids/'),
        ),
    ]
