# Generated by Django 4.2.5 on 2023-09-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_userprofile_confirmpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirmpassword',
        ),
    ]
