# Generated by Django 4.2.5 on 2023-10-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('office', 'Office')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('square_footage', models.PositiveIntegerField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_duration', models.CharField(choices=[('1 year', '1 Year'), ('month-to-month', 'Month-to-Month')], max_length=20)),
                ('availability_date', models.DateField()),
                ('furnished', models.BooleanField(default=False)),
                ('property_images', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.userprofile')),
            ],
        ),
    ]
