# Generated by Django 4.2.5 on 2023-10-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_remove_userprofile_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=15)),
                ('currentaddress', models.TextField()),
                ('photoid', models.FileField(upload_to='photoids/')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.userprofile')),
            ],
        ),
    ]
