# Generated by Django 4.2.5 on 2023-10-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_userform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
