# Generated by Django 4.2.5 on 2023-10-28 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
