# Generated by Django 4.2.5 on 2023-10-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_alter_property_property_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_images',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_name',
        ),
    ]
