# Generated by Django 4.2.5 on 2023-11-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_propertyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
