# Generated by Django 4.2.5 on 2023-11-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='category',
            field=models.CharField(blank=True, default='unspecified', max_length=50, null=True),
        ),
    ]
