# Generated by Django 4.2.5 on 2023-11-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_property_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_footage',
        ),
    ]
