# Generated by Django 4.2.5 on 2023-11-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_remove_property_bathrooms_remove_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(choices=[('swimming-pool', 'Swimming Pool'), ('gym', 'Gym'), ('parking', 'Parking'), ('wifi', 'Wi-Fi'), ('laundry', 'Laundry'), ('ac', 'Air Conditioning')], max_length=50)),
                ('squarefootage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('stories', models.PositiveIntegerField(blank=True, null=True)),
                ('acresofland', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balcony', models.BooleanField(blank=True, null=True)),
                ('parking_area', models.BooleanField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rental.property')),
            ],
        ),
    ]
