# Generated by Django 4.2.5 on 2023-11-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='parking_area',
        ),
    ]
