# Generated by Django 4.2.5 on 2023-11-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_amenity_balcony_amenity_parking_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
