# Generated by Django 4.2.5 on 2023-11-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_amenity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
