# Generated by Django 4.2.5 on 2023-11-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='parkingspace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
