# Generated by Django 4.2.5 on 2023-11-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_alter_amenity_parkingspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='squarefootage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
