# Generated by Django 4.2.5 on 2023-11-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_alter_amenity_squarefootage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
