# Generated by Django 4.2.5 on 2023-11-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0026_delete_amenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squarefootage', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('stories', models.PositiveIntegerField(blank=True, null=True)),
                ('acresofland', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rentspace', models.CharField(blank=True, choices=[('full', 'Full'), ('partial', 'Partial')], max_length=8, null=True)),
                ('noofrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('parkingspace', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('acrescent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rental.property')),
            ],
        ),
    ]
