# Generated by Django 4.2.5 on 2023-11-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0027_amenity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
