# Generated by Django 4.2.5 on 2023-11-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
