# Generated by Django 4.2.5 on 2023-11-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0031_propertydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
