# Generated by Django 4.2.5 on 2023-11-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0032_property_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, to='rental.property'),
        ),
    ]
