# Generated by Django 4.2.5 on 2023-11-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0033_profile_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
    ]
