# Generated by Django 4.2.5 on 2023-11-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0035_rentalrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalRequest',
        ),
    ]
