# Generated by Django 4.2.5 on 2023-11-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0038_rentalrequest_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='approval_status',
        ),
    ]
