# Generated by Django 4.2.5 on 2023-11-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0041_leaseagreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='tenant',
        ),
    ]
