# Generated by Django 4.2.5 on 2023-11-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0042_remove_leaseagreement_landlord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='due_date',
        ),
    ]
