# Generated by Django 4.2.5 on 2023-11-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0044_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
