# Generated by Django 4.2.5 on 2023-12-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0046_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='in_cart',
        ),
    ]
