# Generated by Django 4.2.5 on 2023-12-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0050_remove_transaction_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rent_amount',
        ),
    ]
