# Generated by Django 4.2.5 on 2023-12-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0052_transaction_rent_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='security_deposit',
        ),
    ]
