# Generated by Django 4.2.5 on 2023-12-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0053_remove_transaction_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
