# Generated by Django 4.2.5 on 2023-12-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0057_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
