# Generated by Django 4.2.5 on 2024-02-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0064_serviceproviderprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='experience',
            field=models.IntegerField(max_length=15),
        ),
    ]
