# Generated by Django 4.2.5 on 2024-02-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0070_property_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rented',
        ),
    ]
