# Generated by Django 4.2.5 on 2024-02-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0071_remove_property_rented'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=255, verbose_name='Razorpay Payment ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.profile', verbose_name='User')),
            ],
        ),
    ]
