# Generated by Django 4.2.5 on 2024-02-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0072_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
