# Generated by Django 4.2.5 on 2024-02-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0076_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
