# Generated by Django 4.2.5 on 2024-02-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0079_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='user',
        ),
    ]
