# Generated by Django 4.2.5 on 2024-02-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0080_remove_serviceproviderprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProviderProfile',
        ),
        migrations.RemoveField(
            model_name='service',
            name='provider',
        ),
    ]
