# Generated by Django 4.2.5 on 2024-02-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0082_serviceproviderprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
