# Generated by Django 4.2.5 on 2024-02-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0083_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_category', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('service_provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.serviceproviderprofile')),
            ],
        ),
    ]
