# Generated by Django 4.2.5 on 2024-02-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0084_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
