# Generated by Django 4.2.5 on 2024-02-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0085_alter_service_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='property_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
