# Generated by Django 4.2.5 on 2024-02-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0086_alter_service_location_alter_service_property_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
