# Generated by Django 4.2.5 on 2024-02-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0088_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
