# Generated by Django 4.2.5 on 2024-02-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0092_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
