# Generated by Django 4.2.5 on 2024-02-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0094_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
