# Generated by Django 4.2.5 on 2024-02-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0096_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
