# Generated by Django 4.2.5 on 2024-02-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0098_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
