# Generated by Django 4.2.5 on 2024-02-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0100_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
