# Generated by Django 4.2.5 on 2024-02-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0102_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.profile')),
            ],
        ),
    ]
