# Generated by Django 4.2.5 on 2024-02-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0103_propertyfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyFeedback',
        ),
    ]
