# Generated by Django 4.2.5 on 2024-03-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0110_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
