# Generated by Django 4.2.5 on 2024-03-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0111_servicerequest_scheduled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='scheduled_time',
        ),
    ]
