# Generated by Django 4.2.5 on 2024-03-01 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0114_servicerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
