# Generated by Django 4.2.5 on 2024-03-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0116_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='schedule_time',
        ),
    ]
