# Generated by Django 4.2.5 on 2024-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0117_remove_servicerequest_schedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='schedule_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='schedule_time',
            field=models.TimeField(null=True),
        ),
    ]
