# Generated by Django 4.2.5 on 2024-03-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0120_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
