# Generated by Django 4.2.5 on 2024-03-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0122_service_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.servicerequest')),
            ],
        ),
    ]
