# Generated by Django 4.2.5 on 2024-03-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0124_scheduledservice_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledservice',
            name='is_paid',
        ),
    ]
