# Generated by Django 4.2.5 on 2024-03-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0125_remove_scheduledservice_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledservice',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
