# Generated by Django 4.2.5 on 2024-03-12 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0127_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(choices=[('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Retired', 'Retired')], max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_address', models.TextField()),
                ('nearest_bank', models.CharField(max_length=255)),
                ('net_monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='rental.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
