# Generated by Django 4.2.5 on 2024-03-17 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0128_loanapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propertysell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('amenities', models.TextField()),
                ('contact_information', models.CharField(max_length=100)),
                ('property_images', models.ImageField(upload_to='property_images/')),
                ('ownership', models.CharField(max_length=20)),
                ('plot_area', models.CharField(max_length=20)),
                ('constructed_year', models.IntegerField()),
                ('ready_to_move', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.userprofile')),
            ],
        ),
    ]
