# Generated by Django 4.2.5 on 2024-03-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0130_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
