# Generated by Django 4.2.5 on 2024-04-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0136_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='property',
        ),
    ]
