# Generated by Django 4.2.5 on 2024-04-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0137_remove_loanapplication_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanApplication',
        ),
    ]
